# Generated by Django 5.2.5 on 2025-08-19 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
