# Generated by Django 5.2.5 on 2025-08-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='favourite',
            new_name='favourites',
        ),
    ]
